# Generated by Django 5.1.1 on 2024-10-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
